name: Build and publish AsyncAPI

inputs:
  file-path:
    required: true
    type: string
  target-directory:
    required: true
    type: string
  SSH_DEPLOY_KEY:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Validating AsynAPI
      uses: bitvavo/reusable-workflows/actions/validate-asyncapi@master
      with:
        file-path: ${{ inputs.file-path }}

    - name: Generate Swagger UI
      uses: docker://asyncapi/github-action-for-generator:2.0.0
      with:
        template: '@asyncapi/html-template@0.9.0'
        output: ${{ inputs.target-directory }}
        filepath: ${{ inputs.file-path }}

    - name: Push to asyncapi-swagger
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ inputs.SSH_DEPLOY_KEY }}
      with:
        source-directory: ${{ inputs.target-directory }}
        destination-github-username: bitvavo
        destination-repository-name: asyncapi-swagger
        target-branch: master
        target-directory: ${{ inputs.target-directory }}