name: Build and publish AsyncAPI

inputs:
  file-path:
    required: true
    type: string
  target-directory:
    required: true
    type: string
secrets:
  SSH_DEPLOY_KEY:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Validate AsyncAPI
      uses: bitvavo/reusabled-workflows/actions/validate-asyncapi.yaml

    - name: Generate Swagger UI
      uses: docker://asyncapi/github-action-for-generator:2.0.0
      with:
        template: '@asyncapi/html-template@0.9.0'
        output: swagger-ui
        filepath: ${{ inputs.file-path }}

    - name: Push to asyncapi-swagger
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: swagger-ui
        destination-github-username: bitvavo
        destination-repository-name: asyncapi-swagger
        target-branch: master
        target-directory: ${{ inputs.target-directory }}